---
- name: test additional modules
  hosts: all
  vars:
    php_sury_version: "{{ lookup('env', 'MOLECULE_PHP_VERSION') | default('8.1', true) }}"
    php_sury_a2mod_ignore_configcheck: true
    php_sury_a2mod_ignore_errors: true
    php_sury_remove_packages:
      - php-apcu
    php_sury_additional_packages:
      - php{{ php_sury_version }}-mysql
      - php{{ php_sury_version }}-apcu
  tasks:
    - name: "Include role"
      include_role:
        name: "{{ lookup('env', 'MOLECULE_ROLE_NAME') | default('ansible-php-sury', true) }}"
