---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  vars:
    php_sury_version: "{{ lookup('env', 'MOLECULE_PHP_VERSION') | default('8.1', true) }}"
  tasks:
    - name: copy test script
      ansible.builtin.copy:
        dest: "{{ php_sury_wwwdir | default('/var/www/html') }}/pv.php"
        content: '<?php echo PHP_MAJOR_VERSION . "." . PHP_MINOR_VERSION; ?>'
    - name: register  php version
      set_fact:
        _phpv: "{{ lookup('ansible.builtin.url', 'http://'+ansible_default_ipv4.address+'/pv.php') }}"
    - name: debug php version
      debug:
        var: _phpv
    - name: debug expected php version
      debug:
        var: php_sury_version
    - name: test results
      assert:
        that:
          - _phpv == php_sury_version
